### ISSUE TITLE
A few tricky parts about set up

### ISSUE THREAD

**Issue by andybak** [kwea123/nerf_Unity#1]
1. If Unity is opened before you've downloaded the separate assets it deletes the .meta files and you therefore lose any import settings for those files. Maybe tell people to download them before they open Unity
2. Make it clear that the assets have to be placed in the root of Assets. Anywhere else and they won't link to the correct .meta files.

**Comment by kwea123** [comment]
Thanks, I added in readme. Apart from that, can you manipulate the scenes correctly?

**Comment by andybak** [comment]
Yes. I'm about to try it in VR and then I'm excited to try and generate my own volumes.

One things that would be nice is opacity control for the volume renderer.

**Comment by kwea123** [comment]
You can edit the shader and add a factor to multiply the opacity here:
https://github.com/kwea123/nerf_Unity/blob/e7bfda39b98dbf5b773381b2459ef99b130f0096/Assets/Shaders/volumeShad2.shader#L115-L125
