### ISSUE TITLE
Mixed Reality demo volumes missing

### ISSUE THREAD

**Issue by flaime-ai** [kwea123/nerf_Unity#2]
Hi, great work on the project!
I can't seem to find the T-Rex and Triceratops vols either in the repo or the release downloads, so can't get the Mixed reality demo to work. 

Are these files included anywhere?

Also, I was wondering if there are any instructions to export volumes from NeRFs made using your NeRF repo?

Thanks

**Comment by kwea123** [comment]
They are natively included in the project I think. The files are located [here](https://github.com/kwea123/nerf_Unity/tree/master/Assets/StreamingAssets)
For mixed reality, these are not volumes, they are just `png` image file and `bytes` depth file, which are loaded as `Texture2D`

I recently added the instruction [here](https://github.com/kwea123/nerf_pl/blob/master/README_Unity.md). You need to watch my video for mesh extraction first, it helps to understand the procedure. Please let me know if anything is unclear, I know it becomes little messy after I add these unity plugins; at the same time I want to keep the code concise, so I might miss some important instructions.

**Comment by flaime-ai** [comment]
Thanks - I just released that it may be because I'm running Unity on Linux and I think there's a problem with it picking up the streaming assets. 

```
Cannot connect to destination host
UnityEngine.Debug:Log(Object)
<GetTex>d__10:MoveNext() (at Assets/DepthRender.cs:25)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr) (at /home/builduser/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)

```
I'm investigating now, will update when I've managed to get it working

**Comment by flaime-ai** [comment]
Also, thanks for those instructions, didn't spot them before. Will work trough them and let you know

**Comment by kwea123** [comment]
yeah my project is built on Windows, will add that to readme.
Actually the usage of `StreamingAssets` is only because of the online demo. In pure local usage, you can replace the loading part with local paths.

I think you can just drag those files into the missing part of mixed reality.
Edit: Not dragging the files, I mean entering the path to these files.

**Comment by flaime-ai** [comment]
I can confirm that it does work if the assets are loaded locally on linux.

**Comment by endlesswho** [comment]
> I can confirm that it does work if the assets are loaded locally on linux.

follow this links:https://forum.unity.com/threads/unable-to-read-file-in-streamingassets-on-linux-macos-cannot-connect-to-destination-host.783257/ would help! 
change the line of DepthRender.cs in UnityWebRequest.Get to "UnityWebRequest www = UnityWebRequest.Get("file://" + Path.Combine(Application.streamingAssetsPath, path));" works!.
