### ISSUE TITLE
How can i realize realistic mixed reality photos in Unity?

### ISSUE THREAD

**Issue by mrlihellohorld** [kwea123/nerf_Unity#4]
I imported a model, but there are no shadows. Can you help me with this, thanks
![image](https://user-images.githubusercontent.com/31719207/151282373-1dac77f8-8b3c-4fba-97c9-3b0376c6c360.png)

**Comment by kwea123** [comment]
To obtain shadow, you need to use deferred rendering.
Change the camera render path to deferred:
![image](https://user-images.githubusercontent.com/11364490/151287618-39b6668c-b47a-4617-bee4-ab3af0a4e7e1.png)

The shader is already updated to deferred rendering, please tell me if it works. Thanks

**Comment by kwea123** [comment]
![image](https://user-images.githubusercontent.com/11364490/151287773-1a5c49f9-ef17-4db9-9ae0-d9decdc0a3ce.png)
Works like this on my PC

**Comment by mrlihellohorld** [comment]
thank you for your reply. First I am in my modified project, Changed the camera render path to deferred, there is no shadows.
![image](https://user-images.githubusercontent.com/31719207/151298546-c8a2e119-e919-49b5-a153-1d7547558d10.png)
Then I downloaded the original project you posted again，Changed the camera render path to deferred, still no shadow 
![image](https://user-images.githubusercontent.com/31719207/151298633-6a05512c-1b00-49a4-b280-4d149e8ee519.png)

**Comment by mrlihellohorld** [comment]
I redownloaded the project and now there are shadows. thank you very much for your help.

![image](https://user-images.githubusercontent.com/31719207/151299820-b1706f44-267d-41af-983d-7b906f1e0a48.png)
can you tell me how you loaded your cartoon model？I downloaded a 3D model, a .fbx file：
![image](https://user-images.githubusercontent.com/31719207/151300317-eab0efe3-c7e5-462e-81b5-b0f209f968e8.png)
I put this file under Assets directory. and modify the mesh Filter. But after running, the model here is incomplete 
![image](https://user-images.githubusercontent.com/31719207/151301417-9624251a-fd77-467d-af29-00f7c40fd259.png)

**Comment by kwea123** [comment]
I'm not sure why the model is incomplete. Can you try another one? E.g. this famous one: https://assetstore.unity.com/packages/3d/characters/robots/space-robot-kyle-4696
If you want cartoon models (mine for example), you can find a lot [here](https://hub.vroid.com/), but these vrm models require [UniVRM](https://github.com/vrm-c/UniVRM) to be able to import to Unity and can easily fail if it's your first attempt, so I would suggest that you try the first solution first.
